//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeTicTacToe.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string UserIdCreator { get; set; }
        public string UserIdOpponent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Board { get; set; }
        public Nullable<int> GameResult { get; set; }
        public Nullable<int> CurrentPlayerIndex { get; set; }
        public string Winner { get; set; }
        public bool IsTerminated { get; set; }
    }
}
